check:
    global:
        branches: 100
        functions: 100
        lines: 100
        statements: 100
instrumentation:
    include-pattern: "**/src/**"
    root: packages
reporting:
    reports:
        - html
        - lcovonly
    dir: .coverage
    watermarks:
        branches: [90, 100]
        functions: [90, 100]
        statements: [90, 100]
        lines: [90, 100]
